name: Build example

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'example/**'

jobs:
  build:
    name: Build example
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: subosito/flutter-action@v2.14.0
        with:
          cache: true
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
          workingDir: example
          webRenderer: canvaskit
          baseHref: /flutter_map_animations/
